### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by pavelzarubin** [stepa1000/my-web-server#5]
Тесты сломаны и не дописаны.

**Comment by pavelzarubin** [comment]
А тебе не нужно тестить логику обращения к базе вообще. Напиши тесты только для чистой логики.

**Comment by stepa1000** [comment]
Такс из за несовместимости миграций и обращений к БД вся программа не работает. В отдельный issues?

**Comment by pavelzarubin** [comment]
Да

**Comment by stepa1000** [comment]
как назначить ревьювера?

**Comment by pavelzarubin** [comment]
![Снимок экрана от 2023-05-31 09-35-50](https://github.com/stepa1000/my-web-server/assets/98732727/bd1ff8f9-af7d-4bb1-b9aa-96f73e6bd0b8)
в разделе ```Reviewers```

**Comment by stepa1000** [comment]
![Screenshot 2023-05-31 12:44:10](https://github.com/stepa1000/my-web-server/assets/39490441/ed98ddad-b04a-4895-b5e8-9a7717c0b8fe)

**Comment by pavelzarubin** [comment]
вводи username и ищи, обычно так работает

**Comment by pavelzarubin** [comment]
тогда забей)
